# 管理端-首页
admin_manage_index:
  path:   /
  controller: App\Controller\Admin\AdminController:index

# 管理端-登录
admin_manage_login:
  path:   /login
  controller: App\Controller\Admin\AuthController:login

# 管理端-退出登录
admin_manage_logout:
  path:   /logout
  controller: App\Controller\Admin\AuthController:logout

# 管理端-修改密码
admin_manage_edit_password:
  path:   /edit-password
  controller: App\Controller\Admin\AuthController:editPassword

# 管理端-统计台
admin_manage_statistical_station:
  prefix: /statistical-station
  resource: 'statistical-station/statistical-station.yaml'
  options:
    permission_group:
    permission_tag: statistical_station
    permission_description: 统计台权限

# 管理端-分类管理
admin_manage_sort:
  prefix: /classify
  resource: 'classify/classify.yaml'
  options:
    permission_group:
    permission_tag: classify
    permission_description: 分类管理权限

# 管理端-用户管理
admin_users_manage:
  prefix:   /users
  resource: 'users/users.yaml'
  options:
    permission_group:
    permission_tag: user
    permission_description: 用户管理权限

# 管理端-博客管理
admin_blog_manage:
  prefix:   /blog
  resource: 'blog/blog.yaml'
  options:
    permission_group:
    permission_tag: blog_manage
    permission_description: 博客管理权限

# 管理端-系统设置
admin_blog_system_setting:
    prefix:   /system-setting
    resource: 'system-setting/system-setting.yaml'
    options:
      permission_group:
      permission_tag: system-setting
      permission_description: 系统设置权限


