# 管理端-首页
admin_manage_index:
  path:   /
  controller: App\Controller\Admin\AdminManageController:index

# 管理端-登录
admin_manage_login:
  path:   /login
  controller: App\Controller\Admin\AuthController:login

# 管理端-退出登录
admin_manage_logout:
  path:   /logout
  controller: App\Controller\Admin\AuthController:logout

# 管理端-修改密码
admin_manage_edit_password:
  path:   /edit-password
  controller: App\Controller\Admin\AuthController:editPassword

# 管理端-统计台
admin_manage_statistical_station:
  prefix: /statistical-station
  resource: 'statistical-station/statistical-station.yaml'

# 管理端-用户管理
admin_users_manage:
  prefix:   /users
  resource: 'users/users.yaml'

# 管理端-博客管理
admin_blog_manage:
  prefix:   /blog
  resource: 'blog/blog.yaml'
