# 首页
admin_blog_manage_label_index:
  path: /
  controller: App\Controller\Admin\BlogManager\LabelManageController::index

# 新建/编辑页面
admin_blog_manage_label_page:
  path: /page
  controller: App\Controller\Admin\BlogManager\LabelManageController::page

# 新建
admin_blog_manage_label_create:
  path: /create
  controller: App\Controller\Admin\BlogManager\LabelManageController::create

# 编辑
admin_blog_manage_label_edit:
  path: /edit
  controller: App\Controller\Admin\BlogManager\LabelManageController::edit

# 删除
admin_blog_manage_label_delete:
  path: /delete
  controller: App\Controller\Admin\BlogManager\LabelManageController::delete