# 博客首页
blog_index:
  controller: App\Controller\Blog\BlogController::index
  path:   /

# 博客分类
blog_types:
  controller: App\Controller\Blog\BlogController::types
  path:   /types

# 博客标签
blog_tags:
  controller: App\Controller\Blog\BlogController::tags
  path:   /tags

# 博客文章
blog_article:
 controller:  App\Controller\Blog\BlogController::blog
 path:    /blog

# 博客登录页面
blog_login_page:
  controller: App\Controller\Blog\BlogController::loginPage
  path: /page

# 博客注册页面
blog_register_page:
  controller: App\Controller\Blog\BlogController::registerPage
  path: /register-page

# 博客登录
blog_login:
  controller: App\Controller\Blog\BlogController::login
  path: /login

# 博客注册
blog_register:
  controller: App\Controller\Blog\BlogController::register
  path: /register

# 博客评论
blog_comment:
  controller: App\Controller\Blog\BlogController::comment
  path: /comment



