# 角色列表
admin_manage_admin_role_index:
  path:   /
  controller: App\Controller\Admin\AdminRoleController:roleIndex

# 新建/编辑角色
admin_manage_admin_role_role:
  path:   /edit
  controller: App\Controller\Admin\AdminRoleController:role

# 角色设置权限
admin_manage_admin_role_permission:
  path:   /permission
  controller: App\Controller\Admin\AdminRoleController:rolePermission

# 删除角色
admin_manage_admin_role_del:
  path:   /del
  controller: App\Controller\Admin\AdminRoleController:delRole

# 添加角色权限
admin_manage_admin_role_add_permission:
  path:   /add-permission
  controller: App\Controller\Admin\AdminRoleController:addPermissionToRole

# 移除角色权限
admin_manage_admin_role_remove_permission:
  path:   /remove-permission
  controller: App\Controller\Admin\AdminRoleController:removePermissionToRole

# 添加角色到角色
admin_manage_admin_role_add_role:
  path:   /add-role
  controller: App\Controller\Admin\AdminRoleController:addRoleToRole

# 移除角色到角色
admin_manage_admin_role_remove_role:
  path:   /remove-role
  controller: App\Controller\Admin\AdminRoleController:removeRoleToRole