# 博客管理-文章管理
admin_blog_manage_article:
  prefix: /article
  resource: 'article/article.yaml'

# 博客管理-评论管理
admin_blog_manage_commentary:
  prefix: /commentary
  resource: 'commentary/commentary.yaml'

# 博客管理-标签管理
admin_blog_manage_label:
  prefix: /label
  resource: 'label/label.yaml'

# 博客管理-收藏管理
admin_blog_manage_collection:
  prefix: /collection
  resource: 'collection/collection.yaml'

# 管理端-角色与权限
admin_manage_admin_role:
  resource: "admin-role-manage.yaml"
  prefix:   /admin-role

# 管理端-账号与角色
admin_manage_admin_user:
  resource: "admin-user-manage.yaml"
  prefix:   /admin-user