# 博客管理-文章管理
admin_blog_manage_article:
  prefix: /article
  resource: 'article/article.yaml'

# 博客管理-评论管理
admin_blog_manage_commentary:
  prefix: /commentary
  resource: 'commentary/commentary.yaml'

# 博客管理-标签管理
admin_blog_manage_label:
  prefix: /label
  resource: 'label/label.yaml'