# 博客管理-文章管理-首页
admin_blog_manage_article_index:
  path: /
  controller: App\Controller\Admin\BlogManager\ArticleManagerController::index

# 新建/编辑页面
admin_blog_manage_article_page:
  path: /page
  controller: App\Controller\Admin\BlogManager\ArticleManagerController::page

# 新建
admin_blog_manage_article_create:
  path: /create
  controller: App\Controller\Admin\BlogManager\ArticleManagerController::create

# 编辑
admin_blog_manage_article_edit:
  path: /edit
  controller: App\Controller\Admin\BlogManager\ArticleManagerController::edit