admin:
  resource: "routing/admin/admin.yaml"
  prefix:   /admin
  options:
    platform: admin

upload:
  resource: "routing/upload/upload.yaml"
  prefix:   /upload

captcha:
  resource: "routing/captcha/captcha.yaml"
  prefix:   /captcha

blog:
  resource: "routing/blog/blog.yaml"
  prefix:   /