# 首页
admin_blog_manage_commentary_index:
  path: /
  controller: App\Controller\Admin\BlogManager\CommentaryController::index

# 删除
admin_blog_manage_commentary_delete:
  path: /delete
  controller: App\Controller\Admin\BlogManager\CommentaryController::delete